/*global systemDictionary:true */
'use strict';
systemDictionary = {
    "DuoFern Stick settings": {"en": "DuoFern Stick settings", "de": "DuoFern Stick Einstellungen", "ru": "Настройки DuoFern Stick", "pt": "Configurações do DuoFern Stick", "nl": "DuoFern Stick instellingen", "fr": "Paramètres DuoFern Stick", "it": "Impostazioni DuoFern Stick", "es": "Ajustes de DuoFern Stick", "pl": "Ustawienia DuoFern Stick", "uk": "Налаштування DuoFern Stick", "zh-cn": "DuoFern Stick 设置"},
    "Configure the local Rademacher DuoFern USB stick. Standard baud rate is 115200.": {"en": "Configure the local Rademacher DuoFern USB stick. Standard baud rate is 115200.", "de": "Konfiguration des lokalen Rademacher DuoFern USB-Sticks. Standard-Baudrate ist 115200.", "ru": "Настройте локальный USB-стик Rademacher DuoFern. Стандартная скорость 115200.", "pt": "Configure o stick USB Rademacher DuoFern local. A taxa padrão é 115200.", "nl": "Configureer de lokale Rademacher DuoFern USB-stick. De standaard baudrate is 115200.", "fr": "Configurez la clé USB Rademacher DuoFern locale. Le débit standard est 115200.", "it": "Configura la chiavetta USB Rademacher DuoFern locale. La velocità standard è 115200.", "es": "Configure el USB Stick Rademacher DuoFern local. La velocidad estándar es 115200.", "pl": "Skonfiguruj lokalny stick USB Rademacher DuoFern. Standardowa szybkość to 115200.", "uk": "Налаштуйте локальний USB-стик Rademacher DuoFern. Стандартна швидкість 115200.", "zh-cn": "配置本地 Rademacher DuoFern USB Stick。标准波特率为 115200。"},
    "Serial port": {"en": "Serial port", "de": "Serieller Port", "ru": "Последовательный порт", "pt": "Porta serial", "nl": "Seriële poort", "fr": "Port série", "it": "Porta seriale", "es": "Puerto serie", "pl": "Port szeregowy", "uk": "Послідовний порт", "zh-cn": "串口"},
    "Baud rate": {"en": "Baud rate", "de": "Baudrate", "ru": "Скорость передачи", "pt": "Taxa de transmissão", "nl": "Baudrate", "fr": "Débit en bauds", "it": "Baud rate", "es": "Velocidad en baudios", "pl": "Szybkość transmisji", "uk": "Швидкість передачі", "zh-cn": "波特率"},
    "Dongle serial": {"en": "Dongle serial", "de": "Dongle-Seriennummer", "ru": "Серийный номер донгла", "pt": "Número de série do dongle", "nl": "Dongle-serienummer", "fr": "Numéro de série du dongle", "it": "Seriale del dongle", "es": "Número de serie del dongle", "pl": "Numer seryjny dongla", "uk": "Серійний номер донгла", "zh-cn": "加密狗序列号"},
    "Must usually start with 6F.": {"en": "Must usually start with 6F.", "de": "Muss normalerweise mit 6F beginnen.", "ru": "Обычно должен начинаться с 6F.", "pt": "Normalmente deve começar com 6F.", "nl": "Moet meestal beginnen met 6F.", "fr": "Doit généralement commencer par 6F.", "it": "Di solito deve iniziare con 6F.", "es": "Normalmente debe empezar por 6F.", "pl": "Zwykle musi zaczynać się od 6F.", "uk": "Зазвичай має починатися з 6F.", "zh-cn": "通常必须以 6F 开头。"},
    "Automatically create devices": {"en": "Automatically create devices", "de": "Geräte automatisch anlegen", "ru": "Автоматически создавать устройства", "pt": "Criar dispositivos automaticamente", "nl": "Apparaten automatisch aanmaken", "fr": "Créer les appareils automatiquement", "it": "Crea automaticamente i dispositivi", "es": "Crear dispositivos automáticamente", "pl": "Automatycznie twórz urządzenia", "uk": "Автоматично створювати пристрої", "zh-cn": "自动创建设备"},
    "Request status on adapter start": {"en": "Request status on adapter start", "de": "Status beim Adapterstart abfragen", "ru": "Запрашивать статус при запуске адаптера", "pt": "Solicitar status ao iniciar o adaptador", "nl": "Status opvragen bij adapterstart", "fr": "Demander l’état au démarrage de l’adaptateur", "it": "Richiedi lo stato all’avvio dell’adattatore", "es": "Solicitar estado al iniciar el adaptador", "pl": "Żądaj statusu przy starcie adaptera", "uk": "Запитувати стан під час запуску адаптера", "zh-cn": "适配器启动时请求状态"},
    "Preserve values when telegrams are incomplete": {"en": "Preserve values when telegrams are incomplete", "de": "Werte bei unvollständigen Telegrammen beibehalten", "ru": "Сохранять значения при неполных телеграммах", "pt": "Preservar valores quando os telegramas estão incompletos", "nl": "Waarden behouden bij onvolledige telegrammen", "fr": "Conserver les valeurs lorsque les télégrammes sont incomplets", "it": "Mantieni i valori quando i telegrammi sono incompleti", "es": "Conservar valores cuando los telegramas estén incompletos", "pl": "Zachowuj wartości przy niepełnych telegramach", "uk": "Зберігати значення, якщо телеграми неповні", "zh-cn": "电文不完整时保留数值"},
    "Create only supported/observed states per device": {"en": "Create only supported/observed states per device", "de": "Nur unterstützte/erkannte States je Gerät anlegen", "ru": "Создавать только поддерживаемые или обнаруженные состояния для устройства", "pt": "Criar apenas estados suportados ou observados por dispositivo", "nl": "Alleen ondersteunde of waargenomen states per apparaat aanmaken", "fr": "Créer uniquement les états pris en charge ou observés par appareil", "it": "Crea solo stati supportati o osservati per dispositivo", "es": "Crear solo estados admitidos u observados por dispositivo", "pl": "Twórz tylko obsługiwane lub wykryte stany na urządzenie", "uk": "Створювати лише підтримувані або виявлені стани для пристрою", "zh-cn": "仅为每个设备创建支持或观察到的状态"},
    "Log raw telegrams": {"en": "Log raw telegrams", "de": "Rohtelegramme protokollieren", "ru": "Журналировать необработанные телеграммы", "pt": "Registrar telegramas brutos", "nl": "Ruwe telegrammen loggen", "fr": "Journaliser les télégrammes bruts", "it": "Registra i telegrammi grezzi", "es": "Registrar telegramas sin procesar", "pl": "Rejestruj surowe telegramy", "uk": "Журналювати необроблені телеграми", "zh-cn": "记录原始电文"}
};
